import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import Navbar from '../components/Navbar';
import Sidebar from '../components/Navbar';
import styles from '../styles/Home.module.css';
import BackgroundImage from "../styles/images/feliphe-schiarolli-hes6nUC1MVc-unsplash.jpg"

const Home: NextPage = () => {
  return (
    <div >
      <Head>
        <title>RainbowKit App</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      

      <main >
        
        

        <div className="hero min-h-screen" style={{ backgroundImage: `url("https://images.unsplash.com/photo-1510531704581-5b2870972060?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1173&q=80")` }}>
  <div className="hero-overlay bg-opacity-60"></div>
  <div className="hero-content text-center text-neutral-content">
    <div className="max-w-md">
      <h1 className="mb-5 text-5xl font-bold">Hello there</h1>
      <p className="mb-5 text-xl">Welcome to liveSchool. <br className='mb-2'/>A platform where teachers live stream content and student can learn with their data protected.</p>
      <button className="btn btn-primary">Get Started</button>
    </div>
  </div>
</div>
      </main>

      <footer className={styles.footer}>
        <a href="https://rainbow.me" target="_blank" rel="noopener noreferrer">
          Made with ❤️ by your frens at 🌈
        </a>
      </footer>
    </div>
  );
};

export default Home;
