import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import LitJsSdk from 'lit-js-sdk'
import Cookies from 'js-cookie'
import { UUIDContext } from '../context'
import { useContext, useState } from 'react';
import Image from 'next/image';

const accessControlConditions = [
  {
    contractAddress: '0xdbc7cb706faef5e4c32d3ee14ed45a0c5573a93a',
    standardContractType: 'ERC1155',
    chain: "polygon",
    method: 'balanceOf',
    parameters: [   
      ':userAddress',
      '4'
    ],
    returnValueTest: {
      comparator: '>',
      value: '0'
    }
  }
]

const Home: NextPage = () => {
  const [connected, setConnected] = useState()
  const { id } = useContext(UUIDContext)

  async function connect() {
    const resourceId = {
      baseUrl: 'http://localhost:3000',
      path: '/protected',
      orgId: "",
      role: "",
      extraData: id
    }

    const client = new LitJsSdk.LitNodeClient({ alertWhenUnauthorized: false })
    await client.connect()
    const authSig = await LitJsSdk.checkAndSignAuthMessage({ chain: 'polygon' })

    await client.saveSigningCondition({ accessControlConditions, chain: 'polygon', authSig, resourceId })
    try {
      const jwt = await client.getSignedToken({
        accessControlConditions, chain: 'polygon', authSig, resourceId: resourceId
      })
      Cookies.set('lit-auth', jwt, { expires: 1 })

    } catch (err) {
      console.log('error: ', err)
    }
    setConnected(true)

  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Page Access</h1>
      {
        !connected && <button onClick={connect}>Connect</button>
      }

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
};

export default Home;
