import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import ControlPanelCourse from '../components/ControlPanelCourse';  
import { useAccount } from 'wagmi';

const Home: NextPage = ({response} :any) => {
  const { address } = useAccount({
    onConnect({ address, isReconnected }) {
      
    },
  });
  return (
    
    <div className='bg-slate-100' >
      <Head>
        <title>live School</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <div className='box'>
          <div></div>
          <div></div>
          <div></div>
          <div></div>
          <div></div>
          <div></div>
        </div>
        <div className='box2'>
          <div></div>
          <div></div>
          <div></div>
          <div></div>
        </div>


        <div className="flex w-full">
  <div className="grid h-20 flex-grow card rounded-box place-items-center">

</div>


</div>

<div className="overflow-x-auto w-5/6  place-content-center place-items-center">
<h1 className='text-4xl text-bold'>Control Panel</h1>
  <table className="table mt-5 w-full place-self-center">
   
    <thead >
      <tr >
        
        <th className='bg-secondary '>Course Name</th>
        <th className='bg-secondary'>NFT ID</th>
        
        <th className='bg-secondary'>Upload Content</th>
        <th className='bg-secondary'>Live Stream</th>
        <th className='bg-secondary'>Access Pass</th>
      </tr>
    </thead>
    <tbody>
{response.map((x: any, i: number) => {
  if (x.teacher == address){
  return(<ControlPanelCourse props={x} key={i}/>)
  }
})}
</tbody>
</table>
</div>

      </main>


    </div>
  );
};

export default Home;

// Triggered on each request
export async function getServerSideProps() {
	// Fetching data from an API
	const res = await fetch('http://localhost:3000/api/getCourses');
    

	const response = await res.json();
  
	// Pass the data to the page via props
	return {props: {response}};
}
