import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { ContentPage } from '../components/ContentPage';
import { withIdentity } from '../components/Authenticator'

const Home: NextPage = () => {

    
  return (
    
    <div className='bg-slate-100'>
      <Head>
        <title>RainbowKit App</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className={styles.main}>
      <div className='box'>
          <div></div>
          <div></div>
          <div></div>
          <div></div>
          <div></div>
          <div></div>
        </div>
        <div className='box2'>
          <div></div>
          <div></div>
          <div></div>
          <div></div>
        </div>
<div className="card flex-shrink-0 w-full max-w-3xl shadow-2xl bg-base-100">
      <div className="card-body">
        <div className='card-title'>Course Creation Form</div>
        <div className="form-control">
          <label className="label">
            <span className="label-text text-lg">Course Name</span>
          </label>
          <input type="text" placeholder="Name" className="input input-bordered input-primary" />
        </div>
        <div className="form-control">
            <label className="label">
                <span className="label-text text-lg">Description</span>
            </label>
            <textarea className="textarea textarea-accent" placeholder="Description"></textarea>
        </div>

        <ContentPage/>

<div className="form-control">
          <label className="label">
            <span className="label-text text-lg">Alumnus #1</span>
          </label>
          <input type="text" placeholder="0x...0fa3bc" className="input input-bordered input-primary" />
        </div>
        <div className="form-control">
          <label className="label">
            <span className="label-text text-lg">Alumnus #2</span>
          </label>
          <input type="text" placeholder="0x...0fa3bc" className="input input-bordered input-accent" />
        </div>
        <div className="form-control">
          <label className="label">
            <span className="label-text text-lg">Alumnus #3</span>
          </label>
          <input type="text" placeholder="0x...0fa3bc" className="input input-bordered input-primary" />
        </div>
        <div className="form-control">
          <label className="label">
            <span className="label-text text-lg">Alumnus #4</span>
          </label>
          <input type="text" placeholder="0x...0fa3bc" className="input input-bordered input-accent" />
        </div>
        <div className="form-control">
          <label className="label">
            <span className="label-text text-lg">Alumnus #5</span>
          </label>
          <input type="text" placeholder="0x...0fa3bc" className="input input-bordered input-primary" />
        </div>
        <div className="form-control mt-6">
          <label htmlFor="my-modal-3" className="btn ">Proceed to order review  <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-arrow-right-short" viewBox="0 0 16 16">
  <path fill-rule="evenodd" d="M4 8a.5.5 0 0 1 .5-.5h5.793L8.146 5.354a.5.5 0 1 1 .708-.708l3 3a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708-.708L10.293 8.5H4.5A.5.5 0 0 1 4 8z"/>
</svg></label>
        </div>
      </div>
    </div>
    <input type="checkbox" id="my-modal-3" className="modal-toggle" />
<div className="modal">
  <div className="modal-box h-11/12 max-h-5xl relative">
    <label htmlFor="my-modal-3" className="btn btn-sm btn-circle absolute right-2 top-2">✕</label>
    <h3 className="text-lg font-bold">Review course creation.</h3>
    <p className="py-4 mb-1">Please check the details before ordering course placement!</p>
    <p>Course Name:</p>
    <p>Start Date:</p>
    <p>End Date:</p>
    <p>Description:</p>
    <p>Alumni:</p>
    <p>Alumni badge:</p>
    
    <div className="form-control mt-5">
  <label className=" label">
  <p className="text-bold">I have reviewd my order</p>
    <input type="checkbox"  className="checkbox  mr-10" />
  </label>
  <button className='btn place-self-end mx-3'>Agree and checkout</button>
</div>
    

  </div>
</div>
      </main>

      <footer className={styles.footer}>
        <a href="https://rainbow.me" target="_blank" rel="noopener noreferrer">
          Made with ❤️ by your frens at 🌈
        </a>
      </footer>
    </div>
  );
};

export default withIdentity(Home);
