
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Link from 'next/link';
import DashboardCourse from '../components/DashboardCourse';  



const Home: NextPage = ({response} :any) => {

  return (
    
    <div className='bg-slate-100'>
      <Head>
        <title>live School</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <div className='box'>
          <div></div>
          <div></div>
          <div></div>
          <div></div>
          <div></div>
          <div></div>
        </div>
        <div className='box2'>
          <div></div>
          <div></div>
          <div></div>
          <div></div>
        </div>
        <div className="overflow-x-auto w-5/6 mt-5 place-content-center place-items-center">
<h1 className='text-4xl text-bold'>User Dashboard - please refer to the POC Page for full lit access control functionality</h1>
<p>Tailwind CSS component covers Wallet signing logic on production.</p>
<Link href='https://liveschool-poc.vercel.app/dashboard' passHref><a target="_blank">POC Dashboard</a></Link>
  <table className="table mt-5 w-full place-self-center">
   
    <thead >
      <tr >
        
        <th className='bg-secondary '>Course Name</th>
        <th className='bg-secondary'>NFT ID</th>
        
        <th className='bg-secondary'></th>
        <th className='bg-secondary'>Locked</th>
      </tr>
    </thead>
    <tbody>
{response.map((x: any, i: number) => {
 
  return(<DashboardCourse props={x} key={i}/>)
})}
</tbody>
</table>
</div>
        <div className="flex w-full">
  <div className="grid h-20 flex-grow card rounded-box place-items-center">

</div>


</div>


      </main>


    </div>
  );
};

// Triggered on each request
export async function getServerSideProps() {
  // Fetching data from an API
  
     
        const res = await fetch('https://live-school.vercel.app/api/getCourses');
        
      
        const response = await res.json();
        
        // Pass the data to the page via props
        return {props: {response}};
    
}

export default Home;
