
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import LitJsSdk from 'lit-js-sdk';
import Cookies from 'js-cookie'
import { UUIDContext } from '../context'
import { useContext, useState } from 'react';
import DashboardCourse from '../components/DashboardCourse';  



const Home: NextPage = ({response} :any) => {

  const [connected, setConnected] = useState<any>(false)
  


  return (
    
    <div className='bg-slate-100'>
      <Head>
        <title>RainbowKit App</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className={styles.main}>
      <div className='box'>
          <div></div>
          <div></div>
          <div></div>
          <div></div>
          <div></div>
          <div></div>
        </div>
        <div className='box2'>
          <div></div>
          <div></div>
          <div></div>
          <div></div>
        </div>
        <div className="overflow-x-auto w-5/6 mt-5 place-content-center place-items-center">
<h1 className='text-4xl text-bold'>User Dashboard</h1>
  <table className="table mt-5 w-full place-self-center">
   
    <thead >
      <tr >
        
        <th className='bg-secondary '>Course Name</th>
        <th className='bg-secondary'>NFT ID</th>
        
        <th className='bg-secondary'></th>
        <th className='bg-secondary'>Locked</th>
      </tr>
    </thead>
    <tbody>
{response.map((x: any) => {
  console.log({x})
  return(<DashboardCourse props={x}/>)
})}
</tbody>
</table>
</div>
        <div className="flex w-full">
  <div className="grid h-20 flex-grow card rounded-box place-items-center">

</div>


</div>


      </main>


    </div>
  );
};

// Triggered on each request
export async function getServerSideProps() {
	// Fetching data from an API
	const res = await fetch('http://localhost:3000/api/getCourses');
    

	const response = await res.json();
  
	// Pass the data to the page via props
	return {props: {response}};
}

export default Home;
