
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useState } from 'react';
import DashboardCourse from '../components/DashboardCourse';  



const Home: NextPage = ({response} :any) => {

  return (
    
    <div className='bg-slate-100'>
      <Head>
        <title>live School</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <div className='box'>
          <div></div>
          <div></div>
          <div></div>
          <div></div>
          <div></div>
          <div></div>
        </div>
        <div className='box2'>
          <div></div>
          <div></div>
          <div></div>
          <div></div>
        </div>
        <div className='mt-5'></div>
       <iframe src="https://liveschool-xmtp-helper.vercel.app/" title="description" className='chat shadow-xl' width="55%" height="800px" ></iframe>


      </main>


    </div>
  );
};

// Triggered on each request
export async function getServerSideProps() {
  // Fetching data from an API
  
     
        const res = await fetch('https://live-school.vercel.app/api/getCourses');
        
      
        const response = await res.json();
        
        // Pass the data to the page via props
        return {props: {response}};
    
}

export default Home;
